"""
Generador de notebooks/02_full_catalog_processing.ipynb
Construye el notebook con nbformat para garantizar JSON válido.
Script de uso único: se borra después de ejecutarse.
"""
import nbformat as nbf
from pathlib import Path

nb = nbf.v4.new_notebook()
nb["metadata"] = {
    "kernelspec": {
        "display_name": "Python 3 (venv)",
        "language": "python",
        "name": "python3",
    },
    "language_info": {"name": "python"},
}

cells = []

# === CELDA 1: Header (markdown) ===
cells.append(nbf.v4.new_markdown_cell(
    "# Notebook 02: Procesamiento del Catálogo Completo\n"
    "\n"
    "**Proyecto:** Lunar Tidal Triggering of Earthquakes  \n"
    "**Autor:** Iván Andrés Mena Contreras  \n"
    "**Fecha:** 2026-04-21\n"
    "\n"
    "## Objetivo\n"
    "Escalar el cálculo de posición lunar a los **~3000 eventos completos** del catálogo USGS\n"
    "(M ≥ 7.0, profundidad ≤ 70 km, 1995–2024), con estrategia robusta de:\n"
    "\n"
    "- **Batching** controlado (rate limiting de JPL Horizons)\n"
    "- **Retry** automático ante fallos transitorios de red\n"
    "- **Caching / checkpointing** cada 100 eventos para no perder progreso si algo falla\n"
    "\n"
    "El dataset resultante (`data/processed/earthquakes_with_moon_final.csv`) será la base\n"
    "para todos los análisis estadísticos posteriores."
))

# === CELDA 2: Imports y configuración ===
cells.append(nbf.v4.new_code_cell(
    "# === Imports estándar ===\n"
    "import requests\n"
    "import pandas as pd\n"
    "import numpy as np\n"
    "from astropy.time import Time\n"
    "from astroquery.jplhorizons import Horizons\n"
    "from datetime import datetime\n"
    "\n"
    "# === Imports adicionales para procesamiento robusto ===\n"
    "from pathlib import Path        # rutas portables\n"
    "import time                     # sleep para rate-limiting + medición de tiempo\n"
    "from tqdm.auto import tqdm      # barra de progreso (auto detecta entorno notebook)\n"
    "\n"
    "# Silenciamos warnings para que el output sea legible.\n"
    "import warnings\n"
    "warnings.filterwarnings('ignore')\n"
    "\n"
    "# === Constantes de rutas ===\n"
    "# Como el notebook se ejecuta desde notebooks/, subimos un nivel con '..'\n"
    "# para llegar a la raíz del proyecto. mkdir es idempotente (no falla si ya existe).\n"
    "DATA_RAW       = Path('..') / 'data' / 'raw'\n"
    "DATA_PROCESSED = Path('..') / 'data' / 'processed'\n"
    "DATA_RAW.mkdir(parents=True, exist_ok=True)\n"
    "DATA_PROCESSED.mkdir(parents=True, exist_ok=True)\n"
    "\n"
    "print(\"Librerías cargadas ✓\")\n"
    "print(f\"DATA_RAW       = {DATA_RAW.resolve()}\")\n"
    "print(f\"DATA_PROCESSED = {DATA_PROCESSED.resolve()}\")"
))

# === CELDA 3: Markdown - Sección 1 ===
cells.append(nbf.v4.new_markdown_cell(
    "## 📡 Sección 1: Descarga del catálogo completo\n"
    "\n"
    "Misma API que en el Notebook 01 (USGS ComCat), pero ahora **traemos TODO** y\n"
    "lo persistimos en `data/raw/earthquakes_full_catalog.csv` antes de empezar a\n"
    "consultar Horizons. Así separamos dos preocupaciones:\n"
    "\n"
    "1. **Capturar el catálogo crudo** (una sola request HTTP, rápida).\n"
    "2. **Enriquecer con luna** (~3000 requests a Horizons, lento → necesita checkpointing).\n"
    "\n"
    "**Nota técnica:** USGS limita cada request a 20 000 eventos. Para `M ≥ 7.0` en 30 años\n"
    "esperamos ~3000 → estamos muy por debajo del límite, no hace falta paginar."
))

# === CELDA 4: Descarga USGS completa ===
cells.append(nbf.v4.new_code_cell(
    "# --- Descarga del catálogo completo M>=7.0, profundidad<=70 km, 1995-2024 ---\n"
    "BASE_URL = \"https://earthquake.usgs.gov/fdsnws/event/1/query\"\n"
    "parametros = {\n"
    "    'format':       'geojson',\n"
    "    'minmagnitude': 7.0,\n"
    "    'maxdepth':     70,\n"
    "    'starttime':    '1995-01-01',\n"
    "    'endtime':      '2024-12-31',\n"
    "}\n"
    "\n"
    "print(\"Descargando catálogo completo desde USGS...\")\n"
    "response = requests.get(BASE_URL, params=parametros, timeout=120)\n"
    "if response.status_code != 200:\n"
    "    raise RuntimeError(\n"
    "        f\"USGS HTTP {response.status_code}: {response.text[:300]}\"\n"
    "    )\n"
    "data = response.json()\n"
    "\n"
    "# --- Parseo del GeoJSON a DataFrame (mismo formato que Notebook 01) ---\n"
    "filas = []\n"
    "for feature in data['features']:\n"
    "    props  = feature['properties']\n"
    "    coords = feature['geometry']['coordinates']  # [lon, lat, depth_km]\n"
    "    filas.append({\n"
    "        'id':        feature['id'],\n"
    "        'time':      pd.to_datetime(props['time'], unit='ms', utc=True),\n"
    "        'latitude':  coords[1],\n"
    "        'longitude': coords[0],\n"
    "        'depth':     coords[2],\n"
    "        'magnitude': props['mag'],\n"
    "        'place':     props['place'],\n"
    "        'type':      props['type'],\n"
    "    })\n"
    "\n"
    "df_full = pd.DataFrame(filas).sort_values('time').reset_index(drop=True)\n"
    "\n"
    "# Persistimos el catálogo crudo (sin posición lunar) en data/raw/.\n"
    "ruta_raw = DATA_RAW / 'earthquakes_full_catalog.csv'\n"
    "df_full.to_csv(ruta_raw, index=False)\n"
    "\n"
    "print(f\"\\n✓ Catálogo guardado: {ruta_raw.resolve()}\")\n"
    "print(f\"  Total eventos  : {len(df_full)}\")\n"
    "print(f\"  Rango temporal : {df_full['time'].min()}  →  {df_full['time'].max()}\")\n"
    "print(\"\\nDistribución de magnitudes (M >= 7.0):\")\n"
    "print(df_full['magnitude'].describe().round(2))"
))

# === CELDA 5: Markdown - Estrategia ===
cells.append(nbf.v4.new_markdown_cell(
    "## 🛡️ Sección 2: Estrategia de cálculo lunar robusto\n"
    "\n"
    "Llamar 3000 veces a un servicio externo desde un script secuencial es delicado.\n"
    "Tres mecanismos protegen el procesamiento:\n"
    "\n"
    "### 1. Caching\n"
    "Persistimos el progreso en `data/processed/earthquakes_with_moon_full.csv` cada\n"
    "**100 eventos**. Si el notebook se cae a mitad (red, kernel, ctrl-C), al volver a\n"
    "ejecutarlo **reanuda desde donde quedó**. No perdemos minutos de cómputo ya hecho.\n"
    "\n"
    "### 2. Rate limiting\n"
    "JPL Horizons no publica un límite estricto, pero la práctica es ≤ 4 req/seg para\n"
    "evitar baneos temporales. Imponemos `time.sleep(0.25)` entre llamadas.\n"
    "\n"
    "### 3. Retry con backoff\n"
    "Si una request a Horizons falla por timeout/red, reintentamos hasta 3 veces con\n"
    "espera de 1 s. Si sigue fallando, marcamos el evento como fallido (NaN) y seguimos\n"
    "con el resto. No abortamos el batch entero por un solo evento.\n"
    "\n"
    "### Tiempo estimado\n"
    "`~3000 eventos × (0.25 s sleep + ~0.5 s red) ≈ 35–60 minutos`. Por eso el\n"
    "checkpointing no es opcional: es el seguro de vida del procesamiento."
))

# === CELDA 6: Función get_moon_position con retry ===
cells.append(nbf.v4.new_code_cell(
    "def get_moon_position(jd, max_retries=3, wait_seconds=1):\n"
    "    \"\"\"\n"
    "    Consulta JPL Horizons para obtener la posición lunar en un Julian Date.\n"
    "\n"
    "    Devuelve un dict con:\n"
    "      - moon_ra          : Ascensión Recta de la Luna (grados)\n"
    "      - moon_dec         : Declinación de la Luna (grados)\n"
    "      - moon_distance_au : distancia Tierra-Luna en unidades astronómicas\n"
    "\n"
    "    Si después de max_retries intentos sigue fallando, los tres campos\n"
    "    se devuelven como None. El caller decide qué hacer (en nuestro caso:\n"
    "    marcar el evento como fallido en el DataFrame y continuar).\n"
    "\n"
    "    Parámetros\n"
    "    ----------\n"
    "    jd : float\n"
    "        Julian Date del instante (ej. 2451545.0 = 1 enero 2000, 12:00 UTC).\n"
    "    max_retries : int\n"
    "        Número total de intentos antes de rendirse.\n"
    "    wait_seconds : float\n"
    "        Segundos de espera entre reintentos.\n"
    "    \"\"\"\n"
    "    last_err = None\n"
    "    for intento in range(max_retries):\n"
    "        try:\n"
    "            obj = Horizons(id='301', location='500', epochs=jd)\n"
    "            eph = obj.ephemerides()\n"
    "            return {\n"
    "                'moon_ra':          float(eph['RA'][0]),\n"
    "                'moon_dec':         float(eph['DEC'][0]),\n"
    "                'moon_distance_au': float(eph['delta'][0]),\n"
    "            }\n"
    "        except Exception as e:\n"
    "            last_err = e\n"
    "            # Si aún quedan reintentos, esperamos y volvemos a intentar.\n"
    "            if intento < max_retries - 1:\n"
    "                time.sleep(wait_seconds)\n"
    "    # Todos los intentos fallaron: devolvemos None y registramos el error.\n"
    "    print(f\"  ⚠ Horizons falló (jd={jd:.5f}): {type(last_err).__name__}: {last_err}\")\n"
    "    return {'moon_ra': None, 'moon_dec': None, 'moon_distance_au': None}\n"
    "\n"
    "# Smoke test rápido: una sola consulta para validar que la función funciona.\n"
    "_test = get_moon_position(2451545.0)  # 1 enero 2000, 12:00 UTC\n"
    "print(f\"Smoke test get_moon_position(JD=2451545.0): {_test}\")"
))

# === CELDA 7: Sistema de caching ===
cells.append(nbf.v4.new_code_cell(
    "# --- Sistema de caching: reanudar progreso si existe checkpoint previo ---\n"
    "ruta_progreso = DATA_PROCESSED / 'earthquakes_with_moon_full.csv'\n"
    "\n"
    "if ruta_progreso.exists():\n"
    "    # Reanudación: cargamos el CSV con lo que ya estaba calculado.\n"
    "    df_work = pd.read_csv(ruta_progreso)\n"
    "    # format='ISO8601' tolera filas con o sin microsegundos (pandas 3.x es\n"
    "    # estricto con la inferencia automática y revienta si la precisión varía).\n"
    "    df_work['time'] = pd.to_datetime(df_work['time'], utc=True, format='ISO8601')\n"
    "    print(f\"📂 Checkpoint encontrado: {ruta_progreso.name}\")\n"
    "    print(\"   Reanudando desde donde se quedó la ejecución anterior.\")\n"
    "else:\n"
    "    # Empezar desde cero: añadimos al df_full las columnas lunares en NaN.\n"
    "    df_work = df_full.copy()\n"
    "    df_work['julian_date']      = np.nan\n"
    "    df_work['moon_ra']          = np.nan\n"
    "    df_work['moon_dec']         = np.nan\n"
    "    df_work['moon_distance_au'] = np.nan\n"
    "    print(\"📂 No hay checkpoint previo. Empezando desde cero.\")\n"
    "\n"
    "# Eventos pendientes: aquellos cuya columna moon_ra todavía es NaN.\n"
    "# Esta lógica es lo que permite reanudar limpiamente desde un checkpoint.\n"
    "mask_pendientes = df_work['moon_ra'].isna()\n"
    "n_total      = len(df_work)\n"
    "n_procesados = int((~mask_pendientes).sum())\n"
    "n_pendientes = int(mask_pendientes.sum())\n"
    "\n"
    "print(f\"\\n   Total eventos en catálogo : {n_total}\")\n"
    "print(f\"   Ya procesados             : {n_procesados}\")\n"
    "print(f\"   Pendientes                : {n_pendientes}\")"
))

# === CELDA 8: Procesamiento con tqdm + checkpointing ===
cells.append(nbf.v4.new_code_cell(
    "# --- Procesamiento masivo con barra de progreso y checkpointing ---\n"
    "CHECKPOINT_EVERY = 100   # guardamos a disco cada 100 eventos procesados\n"
    "SLEEP_BETWEEN    = 0.25  # 4 req/seg máximo (rate limiting Horizons)\n"
    "\n"
    "indices_pendientes = df_work[df_work['moon_ra'].isna()].index.tolist()\n"
    "n_pendientes = len(indices_pendientes)\n"
    "n_ok = 0\n"
    "n_fail = 0\n"
    "inicio = time.time()\n"
    "\n"
    "print(f\"Procesando {n_pendientes} eventos pendientes\")\n"
    "print(f\"  Checkpoint  : cada {CHECKPOINT_EVERY} eventos\")\n"
    "print(f\"  Rate limit  : {SLEEP_BETWEEN}s entre requests\")\n"
    "print(f\"  Retry       : 3 intentos por evento\\n\")\n"
    "\n"
    "pbar = tqdm(indices_pendientes, desc=\"Horizons\", unit=\"evt\")\n"
    "for k, i in enumerate(pbar, start=1):\n"
    "    row = df_work.loc[i]\n"
    "\n"
    "    # 1) Convertir el datetime UTC del terremoto a Julian Date.\n"
    "    t  = Time(row['time'].to_pydatetime(), scale='utc')\n"
    "    jd = float(t.jd)\n"
    "\n"
    "    # 2) Consultar posición lunar (con retry interno).\n"
    "    pos = get_moon_position(jd, max_retries=3, wait_seconds=1)\n"
    "\n"
    "    # 3) Volcar el resultado al DataFrame.\n"
    "    df_work.at[i, 'julian_date']      = jd\n"
    "    df_work.at[i, 'moon_ra']          = pos['moon_ra']\n"
    "    df_work.at[i, 'moon_dec']         = pos['moon_dec']\n"
    "    df_work.at[i, 'moon_distance_au'] = pos['moon_distance_au']\n"
    "\n"
    "    if pos['moon_ra'] is None:\n"
    "        n_fail += 1\n"
    "    else:\n"
    "        n_ok += 1\n"
    "\n"
    "    # 4) Rate limiting: nunca más rápido que ~4 req/seg.\n"
    "    time.sleep(SLEEP_BETWEEN)\n"
    "\n"
    "    # 5) Checkpoint periódico: si el kernel muere ahora, recuperamos casi todo.\n"
    "    if k % CHECKPOINT_EVERY == 0:\n"
    "        df_work.to_csv(ruta_progreso, index=False)\n"
    "        pbar.set_postfix(ok=n_ok, fail=n_fail)\n"
    "\n"
    "# Guardado final (asegura que las últimas <100 filas también queden persistidas).\n"
    "df_work.to_csv(ruta_progreso, index=False)\n"
    "elapsed = time.time() - inicio\n"
    "\n"
    "print(f\"\\n--- Procesamiento terminado ---\")\n"
    "print(f\"Eventos OK     : {n_ok}\")\n"
    "print(f\"Eventos fallo  : {n_fail}\")\n"
    "print(f\"Tiempo total   : {elapsed/60:.1f} min ({elapsed:.0f} s)\")\n"
    "print(f\"CSV guardado en: {ruta_progreso.resolve()}\")"
))

# === CELDA 9: Markdown - Validación ===
cells.append(nbf.v4.new_markdown_cell(
    "## ✅ Sección 3: Validación de datos (QA)\n"
    "\n"
    "Releemos el CSV final desde disco (no confiamos en el DataFrame en memoria) y\n"
    "verificamos:\n"
    "\n"
    "- **Completitud:** ¿cuántos eventos tienen luna calculada vs cuántos quedaron NaN?\n"
    "- **Rango físico:** la distancia Tierra-Luna debe estar en `~0.0024–0.0027 AU`\n"
    "  (≈ 360 000 – 405 000 km, perigeo y apogeo lunares).\n"
    "- **Distribución temporal:** eventos por año (debería ser razonablemente uniforme).\n"
    "- **Distribución de magnitudes:** todas ≥ 7.0 por construcción.\n"
    "- **Sondeo visual:** scatter `distancia_lunar vs magnitud` para ver si salta a la\n"
    "  vista algún patrón (sin todavía hacer estadística rigurosa)."
))

# === CELDA 10: QA + plots ===
cells.append(nbf.v4.new_code_cell(
    "import matplotlib.pyplot as plt\n"
    "\n"
    "# Releer del CSV final (validación auténtica: no usamos df_work en memoria).\n"
    "df_qa = pd.read_csv(ruta_progreso)\n"
    "# format='ISO8601' es necesario en pandas 3.x: las filas mezclan timestamps\n"
    "# con microsegundos (.f) y sin ellos, y la inferencia automática es estricta.\n"
    "df_qa['time'] = pd.to_datetime(df_qa['time'], utc=True, format='ISO8601')\n"
    "\n"
    "n_total_qa = len(df_qa)\n"
    "n_nan      = int(df_qa['moon_ra'].isna().sum())\n"
    "n_ok_qa    = n_total_qa - n_nan\n"
    "\n"
    "print(\"=\" * 60)\n"
    "print(\"QA DEL DATASET COMPLETO\")\n"
    "print(\"=\" * 60)\n"
    "print(f\"Total eventos              : {n_total_qa}\")\n"
    "print(f\"Eventos con luna OK        : {n_ok_qa}\")\n"
    "print(f\"Eventos con NaN en moon_ra : {n_nan}\")\n"
    "print()\n"
    "print(\"Rango distancia Tierra-Luna (AU):\")\n"
    "print(df_qa['moon_distance_au'].describe().round(6))\n"
    "print()\n"
    "print(\"Distribución de magnitudes:\")\n"
    "print(df_qa['magnitude'].describe().round(2))\n"
    "print()\n"
    "print(\"Eventos por año:\")\n"
    "print(df_qa['time'].dt.year.value_counts().sort_index())\n"
    "\n"
    "# --- Plots de overview ---\n"
    "df_ok = df_qa.dropna(subset=['moon_ra']).copy()\n"
    "df_ok['year'] = df_ok['time'].dt.year\n"
    "\n"
    "fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n"
    "\n"
    "# 1) Histograma de magnitudes\n"
    "axes[0].hist(df_ok['magnitude'], bins=30, edgecolor='black')\n"
    "axes[0].set_xlabel('Magnitud')\n"
    "axes[0].set_ylabel('Frecuencia')\n"
    "axes[0].set_title('Distribución de magnitudes (M ≥ 7.0)')\n"
    "\n"
    "# 2) Eventos por año\n"
    "events_por_anio = df_ok.groupby('year').size()\n"
    "axes[1].bar(events_por_anio.index, events_por_anio.values)\n"
    "axes[1].set_xlabel('Año')\n"
    "axes[1].set_ylabel('Nº eventos')\n"
    "axes[1].set_title('Eventos sísmicos M ≥ 7.0 por año')\n"
    "\n"
    "# 3) Distancia lunar vs magnitud (sondeo visual previo a estadística)\n"
    "axes[2].scatter(df_ok['moon_distance_au'], df_ok['magnitude'], alpha=0.5, s=15)\n"
    "axes[2].set_xlabel('Distancia Tierra-Luna (AU)')\n"
    "axes[2].set_ylabel('Magnitud')\n"
    "axes[2].set_title('Distancia lunar vs magnitud (sondeo visual)')\n"
    "\n"
    "plt.tight_layout()\n"
    "ruta_fig = Path('..') / 'results' / 'figures' / '02_catalog_overview.png'\n"
    "ruta_fig.parent.mkdir(parents=True, exist_ok=True)\n"
    "plt.savefig(ruta_fig, dpi=120, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f\"\\n✓ Figura guardada en: {ruta_fig.resolve()}\")"
))

# === CELDA 11: Export final limpio ===
cells.append(nbf.v4.new_code_cell(
    "# --- Export del dataset final solo con eventos completos ---\n"
    "# Filtramos cualquier fila con NaN en las columnas lunares para que el\n"
    "# análisis estadístico posterior trabaje sobre datos limpios.\n"
    "df_final = (\n"
    "    df_qa\n"
    "    .dropna(subset=['moon_ra', 'moon_dec', 'moon_distance_au'])\n"
    "    .reset_index(drop=True)\n"
    ")\n"
    "\n"
    "ruta_final = DATA_PROCESSED / 'earthquakes_with_moon_final.csv'\n"
    "df_final.to_csv(ruta_final, index=False)\n"
    "\n"
    "print(f\"✓ Dataset final guardado: {ruta_final.resolve()}\")\n"
    "print(f\"  Eventos finales : {len(df_final)}\")\n"
    "print(f\"  Columnas        : {list(df_final.columns)}\")\n"
    "print()\n"
    "print(\"Primeras 5 filas:\")\n"
    "print(df_final.head(5).to_string())\n"
    "print()\n"
    "print(f\"Dataset listo: {len(df_final)} eventos con datos completos.\")\n"
    "print(\"Siguiente paso: análisis estadístico exploratorio en Notebook 03\")"
))

nb["cells"] = cells

salida = Path("notebooks/02_full_catalog_processing.ipynb")
salida.parent.mkdir(parents=True, exist_ok=True)
with salida.open("w", encoding="utf-8") as f:
    nbf.write(nb, f)

print(f"OK Notebook escrito en {salida.resolve()}")
print(f"Celdas totales: {len(cells)}")
